**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [6]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

Using Kaggle's public dataset BigQuery integration.
Setup Complete

Use the next code cell to fetch the dataset.

In [7]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [8]:
# List all the tables in the "chicago_crime" dataset
tables = list(client.list_tables(dataset))

# Print number of tables in the dataset
print(len(tables))

1

In [9]:
 num_tables = 1 # Store the answer as num_tables and then run this cell

# Check your answer
q_1.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [10]:
# q_1.hint()
q_1.solution()

Solution:
```python

# List all the tables in the "chicago_crime" dataset
tables = list(client.list_tables(dataset))

# Print number of tables in the dataset
print(len(tables))

num_tables = 1

```

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [23]:
for table in tables:  
    print(table.table_id)
    
# Construct a reference to the "full" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

table.schema

crime

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', None, (), None),
 SchemaField('case_number', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('block', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('iucr', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('primary_type', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('location_description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('arrest', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('domestic', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('beat', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('district', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('ward', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('community_area', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('fbi_code', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('year', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('location', 'STRING', 'NULLABLE', None, (), None)]

In [18]:
# Count columns with TIMESTAMP data type
num_timestamp_columns = 0
for column in table.schema:
    if column.field_type == 'TIMESTAMP':
        num_timestamp_columns += 1

print(num_timestamp_columns)

2

In [12]:
num_timestamp_fields = 2 # Put your answer here

# Check your answer
q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [16]:
q_2.hint()
q_2.solution()

Hint: Begin by fetching the `crime` table. Then take a look at the table schema, and check the field type of each column.  How many times does `'TIMESTAMP'` appear?

Solution:
```python

# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

# Print information on all the columns in the "crime" table in the "chicago_crime" dataset
print(table.schema)

num_timestamp_fields = 2

```

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [14]:
# Write the code here to explore the data so you can find the answer

In [25]:
fields_for_plotting = ['latitude', 'longitude'] # Put your answers here

# Check your answer
q_3.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [26]:
q_3.hint()
q_3.solution()

Hint: Look at the table schema.  There are a couple options, but two of the fields are things commonly used to plot on maps. Both are `'FLOAT'` types. Use quotes around the field names in your answer.

Solution:
```python
fields_for_plotting = ['latitude', 'longitude']
```

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [27]:
# Scratch space for your code
# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

# Preview the first five rows of the "crime" table
client.list_rows(table, max_results=5).to_dataframe()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: Cannot use bqstorage_client if max_results is set, reverting to fetching data with the tabledata.list endpoint.
  if __name__ == "__main__":

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,2680,HK308329,2004-04-17 11:35:00+00:00,106XX S WENTWORTH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,34,49,01A,1176839.0,1834173.0,2004,2022-09-18 04:45:51+00:00,41.700310,-87.628099,"(41.700309589, -87.628099219)"
1,22605,HZ338757,2016-07-06 10:33:00+00:00,003XX W 106TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,34,49,01A,1175896.0,1834634.0,2016,2022-09-18 04:45:51+00:00,41.701596,-87.631538,"(41.701595778, -87.631538348)"
2,27281,JG100440,2023-01-01 09:46:00+00:00,106XX S STATE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,34,49,01A,1178141.0,1834245.0,2023,2023-01-08 03:47:29+00:00,41.700478,-87.623330,"(41.700477811, -87.623329654)"
3,21682,HX539782,2014-12-12 04:57:00+00:00,104XX S STATE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,34,49,01A,1178101.0,1835578.0,2014,2022-08-31 04:51:30+00:00,41.704137,-87.623436,"(41.704136655, -87.623435884)"
4,5001,HR298598,2009-05-02 03:15:00+00:00,105XX S WABASH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,9,49,01A,1178438.0,1835159.0,2009,2022-09-18 04:45:51+00:00,41.702979,-87.622215,"(41.702979231, -87.622214525)"

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*